= Emerald Legacy Collected Rules Documents

:toc:
:toc-placement!:

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Status
image:https://github.com/emerald-legacy/rules-documents/workflows/Rules%20Releases/badge.svg?branch=main["Rules"]
image:https://img.shields.io/github/last-commit/emerald-legacy/rules-documents/main.svg["Last commit"]
image:https://img.shields.io/github/contributors/emerald-legacy/rules-documents.svg["Contributors",link="https://github.com/emerald-legacy/rules-documents/graphs/contributors"]
image:https://img.shields.io/github/issues/emerald-legacy/rules-documents.svg["Issues",link="https://github.com/emerald-legacy/rules-documents/issues"]
image:https://img.shields.io/github/issues-closed/emerald-legacy/rules-documents.svg["Issues closed",link="https://github.com/emerald-legacy/rules-documents/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+"]


== Content
This repository contains all rules documents by Emerald Legacy in asciidoc. They are published to GitHub pages as rendered PDF files.

toc::[]

== How to contribute or participate
If you find a typo, bad formatting, or anything else you think we should improve, please create an issue or a pull-request!

== How to build the documents

Prerequisites:
- Ruby 3.0 or higher
- Bundler gem (`gem install bundler`)

You build the output documents with Rake. That will produce both PDF and HTML files.

First, install the dependencies:

`bundle install`

Then build all rules documents:

`bundle exec rake build`

Or clean and rebuild:

`bundle exec rake clean build`

Available Rake tasks:
- `rake build` - Build all rules documents
- `rake render_rules_documents` - Render all rules documents to PDF and HTML
- `rake copy_images` - Copy the images to the build directory
- `rake clean` - Remove generated HTML and PDF files
- `rake clobber` - Remove the entire build directory

== Maintainers
This repository is currently maintained by Ben Wolf (Hida Amoro, programming-wolf).
